-- V10 OIDC/SSO（040）：外部身份映射 + 认证事件审计 + 授权流程临时状态。
-- 与 SQLite 目录的 JavaMigration（OidcSsoMigration，同版本号 10）成对。

CREATE TABLE IF NOT EXISTS oidc_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issuer VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(255),
    first_login_at TIMESTAMPTZ NOT NULL,
    last_login_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_oidc_identities_issuer_subject UNIQUE (issuer, subject)
);

CREATE INDEX IF NOT EXISTS idx_oidc_identities_username ON oidc_identities (username);

CREATE TABLE IF NOT EXISTS auth_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(32) NOT NULL,
    auth_method VARCHAR(16) NOT NULL,
    username VARCHAR(64),
    external_issuer VARCHAR(255),
    external_subject VARCHAR(255),
    roles VARCHAR(255),
    failure_reason VARCHAR(64),
    source_ip VARCHAR(64),
    trace_id VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_events_created_at ON auth_events (created_at);
CREATE INDEX IF NOT EXISTS idx_auth_events_subject ON auth_events (external_subject, created_at);
CREATE INDEX IF NOT EXISTS idx_auth_events_username ON auth_events (username, created_at);

CREATE TABLE IF NOT EXISTS oidc_auth_requests (
    state VARCHAR(64) PRIMARY KEY,
    nonce VARCHAR(64) NOT NULL,
    pkce_verifier VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);
